apiVersion: v1
kind: Pod
metadata:
  name: pod4
  labels:
    app: helloworld
spec:
  containers:
  - name: java-docker-conatiner
    image: bishaljain18/66847899
    ports:
    - name: nodejs-port
      containerPort: 3000
