apiVersion: v1
kind: Service
metadata:
  name: helloworld-servicee
spec:
  ports:
  - port: 31001
    nodePort: 31003
    targetPort: nodejs-port
    protocol: TCP
  selector:
    app: helloworld
  type: NodePort
